### PR TITLE
Fix Ecosystem CI workflow

### PR DESCRIPTION
**Pull request by gastaldi**
This change should make sure that the default branches are used

### CODE REVIEW

**Review by adutra — APPROVED** [review]
LGTM - we'll probably want to change `adutra` to a DataStax team name later on, but that's fine for now.

**Comment by adutra** [comment]
@gastaldi I probably asked already but have you signed our [CLA](cla.datastax.com) already?

**Comment by gastaldi** [comment]
@adutra yes, I did it some hours ago

**Comment by adutra** [comment]
All good then, thanks for your contribution!

**Pull request merged**
