### PR TITLE
small-rye metrics should not be optional

### PR DESCRIPTION
**Pull request by phact**
2020-07-06 15:26:31,458 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
    at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
    at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:155)
    at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
    at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:301)
    at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:42)
    at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
    at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
    at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:126)
    at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:56)
Caused by: java.lang.RuntimeException: Failed to start quarkus
    at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:487)
    at io.quarkus.runtime.Application.start(Application.java:90)
    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
    at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)
    at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/microprofile/metrics/MetricRegistry
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:372)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:330)
    at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientRecorder.setNoopMetricRegistry(CassandraClientRecorder.java:61)
    at io.quarkus.deployment.steps.CassandraClientProcessor$configureRuntimeProperties415902352.deploy_0(CassandraClientProcessor$configureRuntimeProperties415902352.zig:175)
    at io.quarkus.deployment.steps.CassandraClientProcessor$configureRuntimeProperties415902352.deploy(CassandraClientProcessor$configureRuntimeProperties415902352.zig:36)
    at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:354)
    ... 12 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.metrics.MetricRegistry
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:378)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:330)
    ... 20 more

### CODE REVIEW

**Comment by tomekl007** [comment]
According to the docs https://quarkus.io/guides/writing-extensions#case-1-the-library-uses-mp-metrics
it is a good practice in the quarkus extensions to not include implementation of metrics if it is not needed. We could solve it by adding the API and making it non optional:
```
<groupId>org.eclipse.microprofile.metrics</groupId>
<artifactId>microprofile-metrics-api</artifactId>
```

**Comment by adutra** [comment]
> It is desirable to be able to omit the MP Metrics dependency at runtime, so if possible, the library should be written in a way that it will still work when the MP Metrics dependencies (or at least the implementation, io.smallrye:smallrye-metrics) are unavailable.

The way I read this is: make the dependency not optional, but also make your code work if the dependency is manually excluded by the user. Am I correct @tomekl007 ? I think we are meeting these requirements?

**Comment by tomekl007** [comment]
> > It is desirable to be able to omit the MP Metrics dependency at runtime, so if possible, the library should be written in a way that it will still work when the MP Metrics dependencies (or at least the implementation, io.smallrye:smallrye-metrics) are unavailable.
> 
> The way I read this is: make the dependency not optional, but also make your code work if the dependency is manually excluded by the user. Am I correct @tomekl007 ? I think we are meeting these requirements?

I think that by `unavailable` they meant that the dependency is not present on the classpath, but you are right that if metrics are disabled AND the metrics settings will be disabled the user is able to exclude `smallrye-metrics`

**Comment by absurdfarce** [comment]
+1 to manually including microprofile-metrics-api as an explicit dependency of the extension.  We were bringing this in transitively when quarkus-smallrye-metrics was included and it's definitely required at runtime.  This fits into the docs referenced by @tomekl007 above:

> If the library performs injections of the MetricRegistry, which is not avoidable by introducing an if condition, it will unfortunately not be possible to remove the microprofile-metrics dependency, but it is still possible to avoid the need for smallrye-metrics (which contains the implementation class of the metric registry)

I haven't dug into this too deeply but it looks like the same thing applies to smallrye-health/microprofile-health-api

**Comment by adutra** [comment]
We discussed this offline and we are going to merge this PR for alpha3, then revisit dependency declaration later.

**Pull request merged**
