### PR TITLE
Upgrade to Quarkus 2.0 (fixes #172)

### LINKED ISSUE #172: Upgrade to Quarkus 2.0
The extension currently cannot be compiled against Quarkus 2.0, see https://github.com/quarkusio/quarkus/issues/8593#issuecomment-844722003.

Things to fix:

* A few classes do not compile anymore, mostly due to Vert.x API changes.
* MicroProfile 3.0 is not binary-compatible with 2.x; this requires changes in the driver, see [JAVA-2944](https://datastax-oss.atlassian.net/browse/JAVA-2944).
* It turns out that compilation of the extension with Java 11 unveiled Yet-Another-Cryptic-Class-Loading-Problem with the driver's usage of the ServiceLoader API. I opened [JAVA-2946](https://datastax-oss.atlassian.net/browse/JAVA-2946) to fix that (or find a workaround). On the extension side, this is likely to require #171 as well.

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by ppalaga** [comment]
We'd very much appreciate a cassandra-quarkus release based on Quarkus 2.0.0.CR3 to be able to test with Camel Quarkus and even on Quarkus Platform. Is there any hope for it?

**Comment by adutra** [comment]
Hello @ppalaga, our plans so far were to wait until Quarkus 2.0.0.Final is out, then release the Cassandra extension 1.1.0. As we understand it, this would give us roughly a week for the Quarkus Platform to be updated with the newly-released Cassandra extension. Would that work for you? If not, I guess we could look into releasing against Quarkus 2.0.0.CR3.

**Comment by ppalaga** [comment]
> our plans so far were to wait until Quarkus 2.0.0.Final is out, then release the Cassandra extension 1.1.0. As we understand it, this would give us roughly a week for the Quarkus Platform to be updated with the newly-released Cassandra extension. Would that work for you? 

That worked pretty well so far, but this time I guess the risk of incompatibilities is a bit higher due to so many major upgrades in Quarkus and elsewhere. There is also the new Quarkus platform composition and config https://github.com/quarkusio/quarkus-platform/pull/232 that may or may not work well for you, for us (Camel Quarkus) and for you and us in combination :) All these things are much easier to test on CI with proper releases than with snapshots or similar. A CR release would be very appreciated.

**Comment by adutra** [comment]
We discussed this internally and we should get an RC release for you early next week.

**Comment by ppalaga** [comment]
Thanks! I see there is 1.1.0-rc1. Let me upgrade and test in Camel Quarkus.

**Pull request merged**
