### PR TITLE
Add more configuration settings (fixes #72, fixes #105)

### LINKED ISSUE #72: Add config settings for keyspace and graph name
Just as a feedback for your actual work. I'm using the snapshot of the quarkus-cassandra driver and use it for graph statements. It is actually working, but I have to set the graph name on every statement, cause the property quarkus.cassandra.graph.name is ignored. Such "Standart" properties should be supported.

### LINKED ISSUE #105: Expose advanced.reconnect-on-init and advanced.resolve-contact-points in CassandraClientConfig
The driver option `advanced.reconnect-on-init` is false by default, but it probably makes sense, for microservices architectures to set it to true by default.

The driver option `advanced.resolve-contact-points` is also true by default, but it probably makes sense to set it to false instead.

We could expose it in `CassandraClientConfig` for easier access.

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by adutra** [comment]
@thomasbecker just a heads up that, if this PR is accepted, the settings for authentication will change to:

```
quarkus.cassandra.auth.username = <username>
quarkus.cassandra.auth.password = <password>
```

**Comment by adutra** [comment]
@UnvirtualHH this PR solves #72 so you will have the option to set the graph name in application.properties - if the PR is accepted as is.

**Comment by adutra** [comment]
@tomekl007 after this PR we still have #46 open, we can use that issue to add more authentication options and more importantly, SSL.

**Comment by UnvirtualHH** [comment]
I have successfully tested the graph configuration properties. All working fine.

**Pull request merged**
