### PR TITLE
Trigger eager session initialization at startup (fixes #99)

### LINKED ISSUE #99: Timeout in Execution
G'day, 

I'm using datastax graph exzessive in my application. I changed all code to use reactive programming with Mutiny and using alpha1 of cassandra-quarkus. 

A big problem is, that I often run in following exception:

`2020-06-24 11:00:27,059 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-5,5,main]=Thread[vert.x-eventloop-thread-5,5,main] has been blocked for 3341 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@13/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@13/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1867)
	at java.base@13/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
	at java.base@13/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1894)
	at java.base@13/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:143)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:612)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer.createCassandraClient(CassandraClientProducer.java:64)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.create(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.zig:334)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.create(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.zig:365)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
	at io.quarkus.arc.impl.AbstractSharedContext$$Lambda$499/0x0000000800f30440.apply(Unknown Source)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction$$Lambda$503/0x0000000800f36440.get(Unknown Source)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.arc$delegate(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.zig:93)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.execute(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.zig:282)
	at com.datastax.oss.quarkus.runtime.api.reactive.MutinyGraphReactiveSession.executeReactive(MutinyGraphReactiveSession.java:53)
	at de.grumbl.service.GrumblService.findAllNotBlockedMinified(GrumblService.java:230)
	at de.grumbl.service.GrumblService_ClientProxy.findAllNotBlockedMinified(GrumblService_ClientProxy.zig:571)
	at de.grumbl.controller.GrumblController.getAll(GrumblController.java:60)
	at de.grumbl.controller.GrumblController_RouteHandler_getAll_83d3b1a0d0ed0ce5d294317bafebefddea19561a.invoke(GrumblController_RouteHandler_getAll_83d3b1a0d0ed0ce5d294317bafebefddea19561a.zig:110)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:40)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:15)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$14.handle(VertxHttpRecorder.java:982)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$14.handle(VertxHttpRecorder.java:953)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:39)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$$Lambda$97/0x0000000800caac40.handle(Unknown Source)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:108)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.access$100(HttpAuthorizer.java:26)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:125)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:114)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:68)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniCreate.lambda$item$2(UniCreate.java:205)
	at io.smallrye.mutiny.groups.UniCreate$$Lambda$754/0x00000008010f1040.accept(Unknown Source)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:69)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:114)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.access$100(HttpAuthorizer.java:26)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:125)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:114)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:68)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniCreate.lambda$item$2(UniCreate.java:205)
	at io.smallrye.mutiny.groups.UniCreate$$Lambda$754/0x00000008010f1040.accept(Unknown Source)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:69)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:114)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:91)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:203)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:195)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:101)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.UniCache.lambda$onItem$7(UniCache.java:117)
	at io.smallrye.mutiny.operators.UniCache$$Lambda$1002/0x0000000801217440.accept(Unknown Source)
	at java.base@13/java.util.ArrayList.forEach(ArrayList.java:1507)
	at io.smallrye.mutiny.operators.UniCache.onItem(UniCache.java:117)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator$1.accept(MpJwtValidator.java:54)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator$1.accept(MpJwtValidator.java:49)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.operators.UniCache.lambda$subscribing$0(UniCache.java:37)
	at io.smallrye.mutiny.operators.UniCache$$Lambda$995/0x0000000801210040.run(Unknown Source)
	at io.smallrye.mutiny.operators.UniCache.subscribing(UniCache.java:65)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:101)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:48)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:80)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:17)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:74)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:63)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl$$Lambda$992/0x00000008011d3440.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$779/0x000000080113b440.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@13/java.lang.Thread.run(Thread.java:830)
`

My code looks like following:

Controller:

`@Route(path = "/all", methods = HttpMethod.GET, produces = MediaType.APPLICATION_JSON,
           consumes = MediaType.APPLICATION_JSON, order = 1)
    public void getAll(RoutingExchange ex) {
        service.findAll().subscribe()
                     .with(
                             item -> ex.response().end(item),
                             failure -> ex.response().end());
  }`

Service:

   ```
   private final QuarkusCqlSession session;

    @Inject
    public Service(QuarkusCqlSession quarkusCqlSession) {
        this.session = quarkusCqlSession;
    }

 
public Uni<String> findAll() {
        GraphTraversal<Vertex, Map<Object, Object>> gt = g.V().has("item", "blocked", false).elementMap("itemId", "x", "y", 
   "location", "topic");

        FluentGraphStatement statement = FluentGraphStatement.newInstance(gt).setGraphName("graphName");

        return session.executeReactive(statement).onItem().apply(reactiveGraphNode -> reactiveGraphNode.asMap()).onItem()
                      .apply(this::calculateSize).collectItems().asList().onItem().apply(this::convertListToJson);
    }
```

Maybe this is more related to quarkus/mutiny and I have to post it there, but maybe you see any error in using the quarkus-cassandra library.

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by adutra** [comment]
@UnvirtualHH we think that eager initialization of the session should fix your issue. Would you mind trying out this branch if you have time? Thanks!

**Comment by UnvirtualHH** [comment]
I will test it this evening/tomorrow morning. I've also talked with Clement Escoffier about that issue and he checked it a little bit and we are both not sure if your Cassandra Client is really non-blocking. Maybe you should also check this again and if needed investigate some more work into changing it to non blocking. I'm pretty sure Clement could also help or give you a hint, if it is needed. Maybe I'm totally wrong and your client is already non-blocking, I'm absolut not an expert it in this.

**Comment by adutra** [comment]
> I will test it this evening/tomorrow morning. I've also talked with Clement Escoffier about that issue and he checked it a little bit and we are both not sure if your Cassandra Client is really non-blocking. Maybe you should also check this again and if needed investigate some more work into changing it to non blocking. I'm pretty sure Clement could also help or give you a hint, if it is needed. Maybe I'm totally wrong and your client is already non-blocking, I'm absolut not an expert it in this.

That's a very good question, and we probably should add a note to the docs about being non-blocking.

In short the driver is non-blocking _except_ for the following methods:

1. Blocking API execution methods such as `Session.execute(String)`.
2. `SessionBuilder.build()` when creating the session;

For 1) it's the user responsibility to only use the non-blocking API methods when querying. I think it is your case already if you are using `executeReactive` methods exclusively.

For 2) however, it's indeed tricky: we do offer `SessionBuilder.buildAsync()` but that returns a `CompletionStage` which is I think useless in the context of dependency injection (you would be injecting the future, not the result of that future).

So we've been using the blocking method `SessionBuilder.build()` so far in this extension, and that is why you were having trouble. I think that this will be fixed with this PR since `SessionBuilder.build()` is now being called eagerly at startup, and not inside a Vertx thread.

However if you or @cescoffier have better ideas or any suggestion to improve this aspect of the extension, we would love to hear from you. Thanks!

**Comment by cescoffier** [comment]
I think the `SessionBuilder.buildAsync()` should be ok in @UnvirtualHH's case (if I'm not mistaken it's a reactive route - which explains why you ended up on the event loop.

**Comment by UnvirtualHH** [comment]
@cescoffier `SessionBuilder.buildAsync()` isn't possible to use for me, cause I'm using the injected session instance of the client. 

I will give you all feedback after my integration tests where run and I've intensively checked all cases with this branch.

**Comment by UnvirtualHH** [comment]
@adutra I've tested it for every of my microservices and it works like expected. Also with forced errors that previously raised those blocking failures it works now. Much thanks for your quick fix!

**Comment by absurdfarce** [comment]
The effect of this change is to create the QuarkusCqlSession _on the Quarkus main thread_ at startup time.  In general this seems right since it guarantees a singleton instance (which is what we want for now anyway) and avoids any possibility of trying to do that setup on the Vertx event loop threads.

Note that this also means that the session is created as soon as the app starts and that any failure to successfully create this session will cause the entire app to fail to start successfully.  Again, I don't necessarily think this is a fatal problem... but it's _definitely_ a change in behaviour.  For example, switch the contact points to some made-up IP address and watch the errors fly by when you start the app.  In prior versions this behaviour wouldn't have been seen until somebody tried to access a resource which actually used the session.

I mention this here only to be very explicit about these changes in behaviours and to confirm that we're all right with them.

**Comment by absurdfarce** [comment]
To be clear: my concern here is for an app which contains many JAX-RS resources, only _some_ of which use Cassandra.  Under the prior impl these other resources would be available (and functioning) even if Cassandra was not.  Under the impl contained in this PR this would no longer be the case.  There's certainly an argument that this represents an improvement (in the spirit of failing fast) but it's not _immediately_ clear to me that this is true across the board.

So I'm wondering... should be make this a configurable option users could choose to go to in cases where it affects them?  Keep in mind that in the majority of cases lazy initialization works reasonably well.

**Comment by adutra** [comment]
I am totally on board with you @absurdfarce. Have you seen [JAVA-2832](https://datastax-oss.atlassian.net/browse/JAVA-2832)? I've started the discussion around providing an uninitialized session in the driver API, @olim7t already replied.

> Note that this also means that the session is created as soon as the app starts and that any failure to successfully create this session will cause the entire app to fail to start successfully. 

@olim7t suggested that `advanced.reconnect-on-init` addresses that.

> should be make this a configurable option users could choose to go to in cases where it affects them?

Agreed, I will do that and push a commit shortly.

**Comment by adutra** [comment]
Note that one of @olim7t 's suggestions to avoid eager initialization at startup is the ability to inject `CompletionStage<QuarkusCqlSession>`. 

But I am not sure this is possible. 

First, the deployment module currently requires a `QuarkusCqlSession` instance to register a shutdown hook, see [here](https://github.com/datastax/cassandra-quarkus/blob/bde8d2bccdd39d058b42542e98348061532bef8c/runtime/src/main/java/com/datastax/oss/quarkus/runtime/internal/quarkus/CassandraClientRecorder.java#L41-L46).

Secondly, the Quarkus DI container does not seem very comfortable with injecting generic types, `BeanContainer` has no method to retrieve an instance of a generic type, only instance of a raw `Class`.

But even assuming that we solve these two issues, this may not be the ideal solution. Injecting a stage instead of a session makes it hard to implement service components, especially if the mapper is involved. IOW, it's not possible to inject a mapper or dao instance if all you have at hand is a session future, you have to inject a future of your mapper/dao:

```
@ApplicationScoped
public class FruitReactiveService {

  private final CompletionStage<FruitDaoReactive> fruitDaoStage;

  @Inject
  public FruitReactiveService(CompletionStage<FruitDaoReactive> fruitDaoStage) {
    this.fruitDaoStage = fruitDaoStage;
  }

  public Uni<Void> add(Fruit fruit) {
    return Uni.createFrom()
        .completionStage(fruitDaoStage)
        .onItem()
        .produceUni(dao -> dao.update(fruit));
  }

  public Multi<Fruit> get(String id) {
    return Uni.createFrom()
        .completionStage(fruitDaoStage)
        .onItem()
        .produceMulti(dao -> dao.findById(id));
  }
}
```

So I am playing now with the idea of a lazy wrapper for `QuarkusCqlSession`. This seems to work well for cases where the session itself is injected. The code is [here](https://github.com/datastax/cassandra-quarkus/compare/eager-init...lazy-session?expand=1).

However it doesn't solve the problem when a dao must be constructed and injected. The generated dao code is inherently blocking and blocks until all statements have been prepared.

So it seems that if users want the Object Mapper, they _have_ to accept eager initialization at startup.

**Comment by adutra** [comment]
I'm going to merge this, the user that opened #104 is facing issues with blocked threads.

I also opened #105 for the reconnect-on-init stuff.

**Pull request merged**
