### PR TITLE
Merge runtime and deployment boms (fixes #162)

### LINKED ISSUE #162: Merge runtime and deployment boms
As requested [here](https://groups.google.com/g/quarkus-dev/c/gNlG7zaUKeM/m/rBdSVwPiAAAJ).

### PR DESCRIPTION
**Pull request by adutra**

### CODE REVIEW

**Comment by adutra** [comment]
@aloubyansky As per your recommendation [here](https://groups.google.com/g/quarkus-dev/c/gNlG7zaUKeM/m/rBdSVwPiAAAJ) we are removing our deployment BOM. Would you be kind enough to have a look? Thanks 😊

**Review by aloubyansky — APPROVED** [review]
Sure! Looks clean :) Looking forward to the next quarkus-platform upgrade.

**Comment by aloubyansky** [comment]
BTW, the latest final version of Quarkus core is 1.12.0.Final, just in case.

**Comment by adutra** [comment]
Awesome thank you for the quick review! And yes, I'm going to update the quarkus version too before the next release.

**Pull request merged**
