### PR TITLE
Fix broken cql snippet in quickstart guide

### LINKED ISSUE #121: Fix wrong code snippet in quickstart guide
The [quick start guide](https://quarkus.io/guides/cassandra) has an example where the constructor parameters are in the incorrect order. Notice that STORE_ID should be the first argument:

``` 
  private Fruit convertFromDto(FruitDto fruitDto) {
    return new Fruit(STORE_ID, fruitDto.getName(), fruitDto.getDescription());
  }
``` 

Also the method name has a typo in the online guide.

The github repo version of the doc (cassandra.adoc) is correct. We only need to open a PR against quarkus.io to update the online guide.

### PR DESCRIPTION
**Pull request by thomasdarimont**
Fixes #121

### CODE REVIEW

**Comment by adutra** [comment]
Hi, both CQL statements are valid and create identical tables. The parentheses around the partition key columns are optional.

**Comment by thomasdarimont** [comment]
@adutra a I see, thanks for clarification. Nevertheless, I think that the unnecessary parenthesis could be removed.

Additionally, I think I now know what my actual problem was: 
This cassandra-quarkus/quickstart is referenced by this guide on the quarkus website: https://quarkus.io/guides/cassandra

However the cql statements in the that quarkus guide seem to be outdated ... I tried them first and didn't notice, that the column names (id vs. storeId) don't match and got this exception when trying to add a fruits item in the example app:

```
2020-10-03 12:28:02,981 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /fruits failed, error id: 0832c7a4-24fb-458a-bf53-114ba13094b0-3: org.jboss.resteasy.spi.UnhandledException: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Undefined column name store_id
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Undefined column name store_id
        at com.datastax.oss.driver.api.core.servererrors.InvalidQueryException.copy(InvalidQueryException.java:48)
        at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
        at com.datastax.oss.driver.internal.core.session.SessionWrapper.execute(SessionWrapper.java:115)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
        at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_0dbbabf717d8050879abd423867f7559bf780e91_ClientProxy.execute(CassandraClientProducer_ProducerMethod_createCassandraClient_0dbbabf717d8050879abd423867f7559bf780e91_ClientProxy.zig:717)
        at com.datastax.oss.driver.internal.mapper.DaoBase.execute(DaoBase.java:185)
        at com.datastax.oss.quarkus.demo.FruitDaoImpl__MapperGenerated.update(FruitDaoImpl__MapperGenerated.java:52)
        at com.datastax.oss.quarkus.demo.FruitDaoProducer_ProducerMethod_produceFruitDao_cad50b0a1191c19e7d6e576f19dfa431fe76b2f6_ClientProxy.update(FruitDaoProducer_ProducerMethod_produceFruitDao_cad50b0a1191c19e7d6e576f19dfa431fe76b2f6_ClientProxy.zig:176)
        at com.datastax.oss.quarkus.demo.FruitService.save(FruitService.java:29)
        at com.datastax.oss.quarkus.demo.FruitService_ClientProxy.save(FruitService_ClientProxy.zig:216)
        at com.datastax.oss.quarkus.demo.FruitResource.add(FruitResource.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
        ... 17 more
```

I'll send another PR to the quarkus repo then.

**Comment by adutra** [comment]
> This cassandra-quarkus/quickstart is referenced by this guide on the quarkus website: https://quarkus.io/guides/cassandra

The quarkus website docs are a copy of this document:

https://github.com/datastax/cassandra-quarkus/blob/master/documentation/src/main/asciidoc/cassandra.adoc

If the document above is correct, the only thing you have to do is submit a PR against https://github.com/quarkusio/quarkus/ to update the contents of the copy hosted in the quarkus website:

https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/cassandra.adoc

And thank you for spotting this issue :-) 

(please ping me if you open a PR for the quarkus website)

**Comment by adutra** [comment]
This will be superseded by #149 .

**Pull request closed without merging**
